### ISSUE TITLE
Validation fails for xsi in multiple lines

### ISSUE THREAD

**Issue by brankopetric** [eclipxe13/XmlSchemaValidator#14]
Validation fails for next case:

xsi:schemaLocation="
          http://test.org/schemas/ticket 
          http://localhost:8999/xsd/ticket.xsd
">

but not for:
xsi:schemaLocation="http://test.org/schemas/ticket http://localhost:8999/xsd/ticket.xsd">

New line in xml breaks validation. But it is still valid xml file.

In buildSchemasFromSchemaLocationValue method in SchemaValidator.php

line 175: $parts = array_filter(preg_split('/\s+/', $content) ?: []);

preg_split('/\s+/', $content) - split text by spaces - will return next array:

  0 => ""
  1 => "http://test.org/schemas/ticket"
  2 => "http://localhost:8999/xsd/ticket.xsd"
  3 => "http://test.org/schemas/ticket2"
  4 => "http://localhost:8999/xsd/ticket2.xsd"
  5 => ""

And array_fillter preserved array keys.

so $parts array will be:

  1 => "http://test.org/schemas/ticket"
  2 => "http://localhost:8999/xsd/ticket.xsd"
  3 => "http://test.org/schemas/ticket2"
  4 => "http://localhost:8999/xsd/ticket2.xsd"

so now there is problem with $k:
for ($k = 0; $k < $partsCount; $k = $k + 2) {
            $schemas->create($parts[$k], $parts[$k + 1]);
}
there is no index for $parts[0] and undefined index exception occur.

Easy solution may be to reset keys with:
$parts = array_values($parts);
before loop

**Comment by eclipxe13** [comment]
I think you found a bug, I'm working on a fix.
