### ISSUE TITLE
Do you have a plan support Schematron?

### ISSUE THREAD

**Issue by mean-cj** [eclipxe13/XmlSchemaValidator#18]
Hi eclipxe13

Do you have a plan support Schematron?

ISO Schematron is a rule-based xml validation, language for XmlSchemaValidaton

I'm not sure about this feature need to use with PHP XSLT extension or not.
XSLT extension (Sablotron)

Ref: 
https://github.com/Youniwemi/schematron
https://www.php.net/manual/en/class.xsltprocessor.php

 
Thank you so much.

**Comment by eclipxe13** [comment]
No, sorry. I don't have any plan to support Schematron.

I had made some test but looks like the specification is different enough to consider that the project it is not compatible/adaptable.

XSD are based on `http://www.w3.org/2001/XMLSchema` while Schematron is based on `http://purl.oclc.org/dsdl/schematron`. They simply work different.

On the other hand, the looks similar: You could inspect Schematron schemas to extract `schema` and `include` nodes (in XSD is made on `schemaLocation` attribute) and build a schema that includes all, then ask schematron to validate.
